Update btmysql.php
RedDragonWebDesign/BlueThrust5 pull request #101
Opened 2024-01-24 03:03 UTC by deepend-tildeclub

fixes some variable errors. But also fixes some issues the page was having saving information in some text boxes.   For example if I remember correctly you'd go set a category name and instead of the words you put it would put a 0.

2024-01-24 04:04 UTC, RedDragonWebDesign commented
> For example if I remember correctly you'd go set a category name and instead of the words you put it would put a 0.

What page/form should I use to test this?

2024-01-24 04:57 UTC, deepend-tildeclub commented
> > For example if I remember correctly you'd go set a category name and instead of the words you put it would put a 0.
> 
> What page/form should I use to test this?

Couldn't remember when I submitted.. but realized it when I was working on the next one.. It was a few places but the place I remember for sure was when naming a world clock it would put a number instead of the name that you specified.   

Also think naming / renaming forum categories.   Sorry my memory sucks. the delay from the original fix and me fixing all my other git mishaps makes things a bit foggy.

2024-01-24 05:13 UTC, RedDragonWebDesign commented
Unable to reproduce on the add clock, edit clock, add forum category, or edit forum category pages using the string "Test". Each time the thing was successfully edited. Can you `git checkout master` and find me a steps to reproduce please?

2024-01-24 05:40 UTC, deepend-tildeclub commented
> Unable to reproduce on the add clock, edit clock, add forum category, or edit forum category pages using the string "Test". Each time the thing was successfully edited. Can you `git checkout master` and find me a steps to reproduce please?

Sorry my memory sucks.. Found what the error was originally.  you can find it by trying to add a menu item. and you'll get an error: 

Fatal error: Uncaught ArgumentCountError: mysqli_stmt::bind_param() does not accept unknown named parameters in /home/retrodig/public_html/zarksfallenangels/classes/btmysql.php:105 Stack trace: #0 /home/retrodig/public_html/zarksfallenangels/classes/btmysql.php(105): mysqli_stmt->bind_param() #1 /home/retrodig/public_html/zarksfallenangels/classes/basic.php(178): btMySQL->bindParams() #2 /home/retrodig/public_html/zarksfallenangels/members/include/admin/managemenu/include/downloadoptions.php(5): Basic->get_entries() #3 /home/retrodig/public_html/zarksfallenangels/members/include/admin/addmenuitem.php(114): require_once('...') #4 /home/retrodig/public_html/zarksfallenangels/members/console.php(154): require_once('...') #5 {main} thrown in /home/retrodig/public_html/zarksfallenangels/classes/btmysql.php on line 105

2024-01-25 05:31 UTC, deepend-tildeclub commented
were you able to reproduce it since my last message?    Or is there other issues with this code? :)   Just wondering so I can avoid having to put this fix in place each time I run a fresh copy from master.

2024-01-25 06:39 UTC, RedDragonWebDesign requested changes

2024-01-25 06:39 UTC, RedDragonWebDesign commented on src/classes/btmysql.php
> -		$tmpParams = array_merge(array($strParamTypes), $arrValues);
The fundamental problem is that `if (!call_user_func_array(array($objMySQLiStmt, "bind_param"), $arrParams)) {` doesn't want any array keys in the $arrParam variable, right?

So wouldn't the simplest solution just be to use the function `array_values()` to strip the keys out?

I think you could revert all this back to the old code (except for the comments I added), then do...

`$tmpParams = array_merge(array($strParamTypes), array_values($arrValues));`

Want to test that out and see if that's a good solution?

Let's test this carefully. If we get it wrong, it could break a lot of stuff. The btmysql.php class handles all SQL queries for the entire website.

2024-01-25 15:16 UTC, deepend-tildeclub commented on src/classes/btmysql.php
> -		$tmpParams = array_merge(array($strParamTypes), $arrValues);
Been testing it with your suggested change and so far haven't noticed any regression.

2024-01-25 19:14 UTC, RedDragonWebDesign commented
Will test this one a bit more later then approve. No more changes needed. I have some ideas for more changes, but will save for a future patch :)

2024-01-25 19:35 UTC, deepend-tildeclub commented
> Will test this one a bit more later then approve. No more changes needed. I have some ideas for more changes, but will save for a future patch :)

Nice.. Thanks for all your effort considering your lack of time.  Much appreciated.  I will be getting back to finding issues this evening.  Been a busy day so far :)    Going to also put some more effort into setting up a better dev environment.. My current setup is barely functional.

2024-01-26 04:24 UTC, merged