Update member.php
RedDragonWebDesign/BlueThrust5 pull request #106
Opened 2024-01-24 19:55 UTC by deepend-tildeclub

shows depreciation notice on main page when signed out.

2024-01-24 22:55 UTC, RedDragonWebDesign requested changes

2024-01-24 22:55 UTC, RedDragonWebDesign commented on src/classes/member.php
> +			}
Better to use a [guard clause](https://deviq.com/design-patterns/guard-clause) here. Makes code more readable:

```php
if ($memberID === null) {
	return false;
}

$memberID = $this->MySQL->real_escape_string($memberID);
$result = $this->MySQL->query("SELECT * FROM ".$this->strTableName." WHERE username = '$memberID'");
```

2024-01-24 23:12 UTC, RedDragonWebDesign commented
Is the warning on http://localhost/src/index.php? I don't see it.

2024-01-25 02:10 UTC, deepend-tildeclub commented
> Is the warning on http://localhost/src/index.php? I don't see it.

Kinda frustrating.    I'm not getting the error anymore either.  Wonder if something else being fixed helped sort this issue out somehow.

2024-01-25 04:26 UTC, RedDragonWebDesign commented
Sounds good. Will close for now. Can always reopen if the error comes back.

2024-01-25 04:26 UTC, closed without merging