Update _functions.php
RedDragonWebDesign/BlueThrust5 pull request #108
Opened 2024-01-24 20:18 UTC by deepend-tildeclub

you get these two errors on the page it takes you when you sign out of the website.

Warning: preg_replace(): Compilation failed: unrecognized character follows \ at offset 3 in /home/retrodig/public_html/zarksfallenangels/_functions.php on line 131

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/retrodig/public_html/zarksfallenangels/_functions.php on line 133

2024-01-24 23:17 UTC, RedDragonWebDesign commented
Clicking "Sign Out" in the top right logs me out and quickly redirects me to the homepage. In the blink of an eye. If there were a warning, I would think it would print it, which would mess up the header that does the redirect, and I'd be able to see it.

Any hint for steps to reproduce?

2024-01-25 05:28 UTC, RedDragonWebDesign commented
I found this error. It's not in the logout system, it's when viewing a forum thread.

http://localhost/src/forum/viewtopic.php?tID=1

2024-01-25 05:41 UTC, RedDragonWebDesign requested changes

2024-01-25 05:41 UTC, RedDragonWebDesign commented on src/_functions.php
> +	$strText = preg_replace("/\\[youtube\\](http|https)(:\\/\\/www\\.youtube\\.com\\/watch\\?v=)(.*?)\\[\\/youtube\\]/i", "<iframe class='youtubeEmbed' src='http://www.youtube.com/embed/$3?wmode=opaque'
OK, so the reason this line was originally throwing an error can be demonstrated here:

https://regex101.com/r/h9famE/3

Old versions of PHP were running regex version `PCRE (PHP <7.3)`. You'll notice that `PCRE (PHP <7.3)` is selected in the flavor section, and there are no errors (no red spots in the regular expression.

![image](https://github.com/RedDragonWebDesign/BlueThrust5/assets/43397938/65b12c6c-f3fd-4abd-9736-b860e9ef5408)

But PHP 8.1 runs `PCRE2 (PHP >=7.3)`. If you click on flavor `PCRE2 (PHP >=7.3)`, you'll notice we immediately get a red spot (an error).

![image](https://github.com/RedDragonWebDesign/BlueThrust5/assets/43397938/8a92516f-d667-4e9f-b09c-7225e3735190)

The fix is simply to delete the `\` in front of the word `youtube`.

It looks like your changes break the code even more without fixing it. It becomes a little more obvious at this link which uses your changed regex, which has 4 red spots:

https://regex101.com/r/Zc53Rm/1

<img width="654" alt="image" src="https://github.com/RedDragonWebDesign/BlueThrust5/assets/43397938/b48ee18e-b4b4-4dae-b9d1-7f4b39ac50e0">

Anyway, with this pointed out and with this regex101 tool, think you can update this patch to just remove the appropriate backslashes and change nothing else? I think that's the way to go.

2024-01-25 05:46 UTC, deepend-tildeclub commented
> I found this error. It's not in the logout system, it's when viewing a forum thread.
> 
> http://localhost/src/forum/viewtopic.php?tID=1

Seems it is behaving slightly different then it was earlier today.  I put the _functions.php file back to master and it gives me the errors on the main page logged in or not.   Also also see the errors in the forum thread as you do.

2024-01-25 05:47 UTC, deepend-tildeclub commented on src/_functions.php
> +	$strText = preg_replace("/\\[youtube\\](http|https)(:\\/\\/www\\.youtube\\.com\\/watch\\?v=)(.*?)\\[\\/youtube\\]/i", "<iframe class='youtubeEmbed' src='http://www.youtube.com/embed/$3?wmode=opaque'
> Anyway, with this pointed out and with this regex101 tool, think you can update this patch to just remove the appropriate backslashes and change nothing else? I think that's the way to go.

Thanks.. will look closer at that.. also thanks for the website.  Never heard of regex101.com.  Looks very useful :)

2024-01-26 05:08 UTC, RedDragonWebDesign commented
Alright, I just went ahead and merged a patch that deleted that one backslash from `\youtube` that I mentioned above, because it was causing the only remaining warnings on the forum viewtopic page.

Can you `pull` and `checkout` the latest master branch and see if this patch is still needed? I think we might be able to abandon this patch, unless it fixes something else.

2024-01-27 00:18 UTC, closed without merging