Some fixes
RedDragonWebDesign/BlueThrust5 pull request #88
Opened 2024-01-22 03:26 UTC by deepend-tildeclub

I know I'm not the best at handling git stuff.. I've been just going page by page trying to reduce errors and issues.. Restored some functionality that wasn't working like private messages, managing and editing world clocks without error, Some fixes to reduce issues with creating polls.(poll stuff not completely working yet) More to come soon. If you like I will request a pull request for future changes as well. I'm not going to pretend to be an expert but I really want this application to function fully and then can always take it further after that if you like.

2024-01-22 11:48 UTC, RedDragonWebDesign commented
Has this stuff been broken for a long time, or do you think it was a PHP version thing? What PHP version are you using?

2024-01-22 11:49 UTC, RedDragonWebDesign commented
Usually when you submit a pull request, you will want to create a new branch in git rather than using the master branch. This gives you the ability to submit multiple PRs at the same time just by changing branches. If you use the master branch for all of them, things get messy. No need to change anything for this PR, but a good tip for future PRs.

2024-01-22 11:53 UTC, RedDragonWebDesign commented
In the future, will probably want to split into one PR per feature you worked on. For example, one for private messages, one for world clocks, one for polls. This makes it easier for the reviewer to load it up and test it and reason about it :)

2024-01-22 15:35 UTC, deepend-tildeclub commented
> In the future, will probably want to split into one PR per feature you worked on. For example, one for private messages, one for world clocks, one for polls. This makes it easier for the reviewer to load it up and test it and reason about it :)

I will work on doing that in the future, sorry about that.

2024-01-22 19:46 UTC, RedDragonWebDesign requested changes

2024-01-22 19:46 UTC, RedDragonWebDesign commented on src/classes/btbbcode.php
> -			}
Did you mean to remove this brace? Looks like a syntax error.

2024-01-22 19:49 UTC, RedDragonWebDesign commented on src/classes/btbbcode.php
> -			}
Actually, looking at more commits, the brace is still there, but is indented too much. And also preg_replace( is missing a `);`.

2024-01-22 20:05 UTC, RedDragonWebDesign commented on src/_functions.php
> +$strText = preg_replace("/\[youtube\](http|https)(\\:\\/\\/www\\.youtube\\.com\\/watch\\?v\\=)(.*)\[\/youtube\]/i", "<iframe class='youtubeEmbed' src='http://www.youtube.com/embed/$3?wmode=opaque' fr
Please put the old indentation on these lines back. And in the rest of the files please.

On a lot of the lines, you unindented so that the indentation doesn't match the rest of the file. It also makes the git diffs harder to read.

Please use tabs instead of 4 spaces, to match the rest of this repo.

In a good code editor such as VS Code, you can select all the lines you want to indent, then hit tab as many times as needed, and it will scoot them all over to the right.

You can change from 4 spaces to tabs by clicking at the bottom right of VS Code where it says "Tab Size", and click on "Convert Indentation to Tabs"

2024-01-22 20:15 UTC, RedDragonWebDesign requested changes

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/classes/basic.php
> +public function addNew($arrColumns, $arrValues) {
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/classes/basicorder.php
> +function validateOrder($intOrderNumID, $strBeforeAfter, $blnEdit = false, $intEditOrderNum = "") {
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/classes/btbbcode.php
> -			}
Since this is a syntax error from before you started this patch, I would just comment out $strText by adding `//` to the front of it.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/classes/btmysql.php
> +public function bindParams($objMySQLiStmt, $arrValues) {
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/classes/form.php
> +// Output input
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/classes/member.php
> +protected function getMemberPicture($db_name, $defaultpic, $cssClass = array(), $setWidth = "", $setHeight = "") {
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/classes/news.php
> +public function show() {
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/classes/privatemessage.php
> +public function getRecipients($blnNameOnly=false) {
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/classes/rank.php
> +function refreshImageSize() {
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/forum/recent.php
> +$arrTopics = []; // Initialize $arrTopics as an empty array
No comment needed here. We can tell what it's doing just by reading the code.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/forum/unread.php
> +$arrTopics = []; // Initialize $arrTopics as an empty array
No comment needed here.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/members/console.managelist.list.php
> +require_once("../_setup.php");
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/members/include/polls/createpoll.php
> +if ($countErrors > 0) {
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/members/include/polls/createpoll.php
> +}
Is this a typo? If not, then the indentation of the code below it should be reduced.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/members/include/polls/include/addoption.php
> +if (count($_SESSION['btPollOptionCache'][$pollObj->cacheID]) > 0) {
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/members/include/privatemessages/addfolder.php
> +echo "
Please fix indenting.

2024-01-22 20:15 UTC, RedDragonWebDesign commented on src/members/privatemessages/compose.php
> +        "subject" => array(
Please fix indenting.

2024-01-23 05:40 UTC, RedDragonWebDesign requested changes

2024-01-23 05:40 UTC, RedDragonWebDesign commented on .idea/.gitignore
> +# Default ignored files
Probably shouldn't have code editor settings files committed to the git repo. The proper way to fix this is...

- cut these files into a file outside the repo (to temporarily get them out of the repo, we'll put them back later)
- commit the file deletions in git (`git commit`)
- create a global .gitignore file with the contents `/.idea/` (how to create a global .gitignore: https://stackoverflow.com/a/7335487)

2024-01-23 05:40 UTC, RedDragonWebDesign commented on src/_functions.php
> +	/*
Indentation is wrong. Needs un-indenting.

2024-01-23 05:40 UTC, RedDragonWebDesign commented on src/classes/access.php
> +	/*
Indentation is wrong. Needs un-indenting.

2024-01-23 05:40 UTC, RedDragonWebDesign commented on src/classes/basic.php
> +	/*
Indentation is wrong. Needs un-indenting.

2024-01-23 05:40 UTC, RedDragonWebDesign commented on src/classes/basicorder.php
> +	/*
Indentation is wrong. Needs un-indenting.

2024-01-23 05:47 UTC, RedDragonWebDesign commented
This PR is getting too big. Please don't add any more files to it. Please instead start using git branches as mentioned above, then submit new PRs for groups of files/changes that make sense to group together. Some examples of reasonable groupings:

- fix world clocks
- fix private messages
- fix polls
- fix PHP 8.1 deprecations/notices/warnings in X folder/file

To create a new git branch...

- `git checkout master` - makes sure you're on the master branch, to use it as your "base"
- `git branch fix-world-clocks` - creates a new branch called fix-world-clocks
- make your changes
- `git commit`
- `git push`
- visit https://github.com/RedDragonWebDesign/BlueThrust5
- click the green "Create pull request" button at the top

Rinse and repeat.

Each branch is a snapshot of the file contents at a certain point in time. So if you type `git checkout master` after making the above changes, it will change your local files to match the master branch. This allows us to make a bunch of little forks of the master branch, which is useful for PRs.

2024-01-23 05:49 UTC, deepend-tildeclub commented on .idea/.gitignore
> +# Default ignored files
Yeah sorry.. never used this program before.. Didn't know it'd do that.   Thanks for your patience with me and the help with great explanations.     I usually use a text editor like nano instead.  But figure I should probably try something more capable.

2024-01-23 06:10 UTC, deepend-tildeclub commented
> This PR is getting too big. Please don't add any more files to it. Please instead start using git branches as mentioned above, then submit new PRs for groups of files/changes that make sense to group together. Some examples of reasonable groupings:
> 
>     * fix world clocks
> 
>     * fix private messages
> 
>     * fix polls
> 
>     * fix PHP 8.1 deprecations/notices/warnings in X folder/file
> 
> 
> To create a new git branch...
> 
>     * `git checkout master` - makes sure you're on the master branch, to use it as your "base"
> 
>     * `git branch fix-world-clocks` - creates a new branch called fix-world-clocks. you should pick a name that describes the changes you're about to make.
> 
>     * `git checkout fix-world-clocks`
> 
>     * make your code changes
> 
>     * save your files
> 
>     * `git commit`
> 
>     * `git push`
> 
>     * visit https://github.com/RedDragonWebDesign/BlueThrust5
> 
>     * click the green "Create pull request" button at the top
> 
> 
> Rinse and repeat.
> 
> Each branch is a snapshot of the file contents at a certain point in time. So if you type `git checkout master` after making the above changes, it will change your local files to match the master branch. Your changes to fix-world-clocks will be temporarily gone from your local files, but will still be saved in git's memory. This allows us to make a bunch of little forks of the master branch, which is useful for PRs.

I can definitely do that.  If you like we can just close this PR and I'll resubmit once I've sorted all this out?

2024-01-23 06:11 UTC, RedDragonWebDesign commented
Sure. That will be a lot of work, but if you're willing, that is definitely the most organized way to do it.

2024-01-23 06:12 UTC, deepend-tildeclub commented
> Sure. That will be a lot of work, but if you're willing, that is definitely the most organized way to do it.

I can try my best.

2024-01-23 06:53 UTC, closed without merging